### ISSUE TITLE
What happened to the KAMAR API documentation

### ISSUE THREAD

**Issue by TheDiamondPicks** [TGS-App/Oligo#6]
Hi, sorry that this isn't quite the right place, but there's not really anywhere else to put it now.

I'm just wondering what happened to your documentation about the KAMAR API, it was extremely useful for working with the API, especially for pages that weren't enabled by my school (or the KAMAR demo portal).

**Comment by k-yle** [comment]
hey, unfortunately we were told to remove it, as it wasn't meant to be public information

**Comment by TheDiamondPicks** [comment]
Seems a bit strange on their part to request it to be taken down, considering it's relatively easy to find. Thanks anyway.
